"""Publication-style plots for the S2 steady-state temperature extension.

Python is the exclusive plotting backend. Source data are generated by
scan_s2_steady_temperature_extension.py.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm
import numpy as np
import pandas as pd

SCRIPT = Path(__file__).resolve()
CODE_ROOT = SCRIPT.parents[2]
SRC_ROOT = CODE_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from fusion_tem import device as cfg  # noqa: E402

mpl.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
    "svg.fonttype": "none",
    "pdf.fonttype": 42,
    "font.size": 7,
    "axes.labelsize": 7,
    "axes.titlesize": 7,
    "axes.linewidth": 0.7,
    "xtick.labelsize": 6.2,
    "ytick.labelsize": 6.2,
    "legend.fontsize": 6.2,
    "legend.frameon": False,
    "axes.spines.right": False,
    "axes.spines.top": False,
})

BLUE = "#355C8A"
TEAL = "#4C8C8A"
RED = "#B4473D"
GREY = "#767676"
DARK_GREY = "#404A53"
LIGHT_BLUE = "#DCE7F2"
SCENARIO_COLORS = {"S4": "#A36A2E", "S5": BLUE, "S6": TEAL}
CONTOUR_LEVELS = np.array([5, 10, 12.5, 15, 17.5, 20, 30, 50, 100, 200], dtype=float)
FIXED_COMPARISON_NPW = 30
FIXED_COMPARISON_RJ_NOHM = 10.0
CMAP = mpl.colors.LinearSegmentedColormap.from_list(
    "steady_lcoe", ["#F4F7FB", "#C8D9EA", "#7EA6C9", "#355C8A", "#263550"]
)
CMAP.set_bad("white")
EXPECTED_DEVICE = "arc_16pancake_nuc600"


def centers_to_edges(values: np.ndarray, log: bool = False) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    if log:
        inner = np.sqrt(values[:-1] * values[1:])
        first = values[0] ** 2 / inner[0]
        last = values[-1] ** 2 / inner[-1]
    else:
        inner = 0.5 * (values[:-1] + values[1:])
        first = values[0] - (inner[0] - values[0])
        last = values[-1] + (values[-1] - inner[-1])
    return np.r_[first, inner, last]


def add_delta_contours(
    ax: plt.Axes,
    npw: np.ndarray,
    rj: np.ndarray,
    z_plot: np.ma.MaskedArray,
    label_lines: bool,
) -> None:
    """Overlay shared ΔLCOE contours, highlighting the 10 US$/MWh threshold."""

    finite = np.asarray(z_plot.compressed(), dtype=float)
    if finite.size == 0:
        return
    zmin = float(np.nanmin(finite))
    zmax = float(np.nanmax(finite))
    regular = [level for level in CONTOUR_LEVELS if level != 10 and zmin < level < zmax]
    if regular:
        contours = ax.contour(
            npw, rj, z_plot, levels=regular, colors=DARK_GREY,
            linewidths=0.45, alpha=0.86, zorder=3,
        )
        if label_lines:
            label_levels = [
                level for level in regular
                if level in {5, 15, 20, 50, 100, 200}
            ]
            if zmin >= 15 and 17.5 in regular:
                label_levels.append(17.5)
            if label_levels:
                ax.clabel(
                    contours, levels=label_levels, fmt="%g", inline=True,
                    fontsize=4.6, inline_spacing=2,
                )
    if zmin < 10.0 < zmax:
        threshold = ax.contour(
            npw, rj, z_plot, levels=[10.0], colors=RED,
            linewidths=0.95, zorder=4,
        )
        if label_lines:
            ax.clabel(
                threshold, fmt={10.0: "10"}, inline=True,
                fontsize=5.0, inline_spacing=2,
            )

def save_bundle(fig: plt.Figure, stem: Path) -> None:
    stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(stem.with_suffix(".svg"), bbox_inches="tight")
    fig.savefig(stem.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(stem.with_suffix(".tiff"), dpi=600, bbox_inches="tight")
    fig.savefig(stem.with_suffix(".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_summary(summary: pd.DataFrame, output_dir: Path) -> None:
    s = summary.sort_values("Top_K")
    t = s["Top_K"].to_numpy()
    lcoe = s["LCOE_plant_USD_per_MWh"].to_numpy()
    delta = s["delta_LCOE_global_USD_per_MWh"].to_numpy()
    ref = float(s["global_reference_LCOE_USD_per_MWh"].iloc[0])
    threshold = ref + 10.0

    fig, axes = plt.subplots(1, 2, figsize=(7.20, 2.65), gridspec_kw={"wspace": 0.34})
    ax = axes[0]
    ax.axhspan(ref, threshold, color=LIGHT_BLUE, alpha=0.55, zorder=0)
    ax.axhline(threshold, color=RED, lw=1.0, ls="--")
    ax.plot(t, lcoe, color=BLUE, lw=1.6, marker="o", ms=4.2, mfc="white", mew=1.0)
    for x, y, d in zip(t, lcoe, delta):
        ax.annotate(f"{d:.2f}", (x, y), xytext=(0, 6), textcoords="offset points",
                    ha="center", va="bottom", fontsize=5.8, color=BLUE)
    ax.text(39.6, threshold + 0.15, r"$\Delta$LCOE = 10", ha="right", va="bottom",
            fontsize=6.0, color=RED)
    ax.set_xlim(3.3, 40.9)
    ax.set_ylim(min(lcoe.min() - 0.9, ref - 0.5),
                max(threshold + 1.2, lcoe.max() + 0.9))
    ax.set_xticks(t)
    ax.set_xlabel("Operating temperature (K)")
    ax.set_ylabel(r"Optimized full-plant LCOE (US$ MWh$^{-1}$)")
    ax.set_title("Optimized temperature response", loc="left", fontweight="bold")
    ax.text(-0.16, 1.05, "a", transform=ax.transAxes, fontweight="bold", fontsize=8)
    ax.text(0.02, 0.05, "Numbers above markers: ΔLCOE", transform=ax.transAxes,
            fontsize=5.5, color=GREY)

    ax = axes[1]
    tape = s["Tape_cost_USD"].to_numpy()
    recirc = s["r_cryo_re_pct"].to_numpy()
    base_idx = int(np.where(np.isclose(t, 10.0))[0][0])
    tape_index = tape / tape[base_idx]
    recirc_index = recirc / recirc[base_idx]
    ax.axhline(1.0, color="#B8B8B8", lw=0.8, ls="--", zorder=0)
    ax.plot(t, tape_index, color=BLUE, lw=1.6, marker="o", ms=4.0, label="HTS tape CAPEX")
    ax.plot(t, recirc_index, color=TEAL, lw=1.6, marker="s", ms=3.7, label="Cryogenic recirculation")
    ax.text(40.25, tape_index[-1], "Tape CAPEX", color=BLUE, va="center", fontsize=6.0)
    ax.text(40.25, recirc_index[-1], "Cryogenic load", color=TEAL, va="center", fontsize=6.0)
    ax.set_xlim(3.3, 44.0)
    ax.set_ylim(max(0.0, min(tape_index.min(), recirc_index.min()) - 0.15),
                max(tape_index.max(), recirc_index.max()) * 1.12)
    ax.set_xticks(t)
    ax.set_xlabel("Operating temperature (K)")
    ax.set_ylabel("Index relative to 10 K optimum")
    ax.set_title("Competing economic drivers", loc="left", fontweight="bold")
    ax.text(-0.16, 1.05, "b", transform=ax.transAxes, fontweight="bold", fontsize=8)
    ax.text(0.02, 0.05, "Deterministic model; no uncertainty interval", transform=ax.transAxes,
            fontsize=5.5, color=GREY)

    fig.text(0.50, 0.985, r"S2 steady-state screen; $N_{pw}$ and $R_j$ optimized at each temperature",
             ha="center", va="top", fontsize=7.0)
    save_bundle(fig, output_dir / "s2_steady_temperature_summary")


def plot_heatmaps(grid: pd.DataFrame, summary: pd.DataFrame, output_dir: Path) -> None:
    temps = sorted(grid["Top_K"].unique())
    npw = np.sort(grid["Npw"].unique().astype(float))
    rj = np.sort(grid["R_joint_nOhm"].unique().astype(float))
    xe = centers_to_edges(npw, log=False)
    ye = centers_to_edges(rj, log=True)
    boundaries = np.array([0, 1, 2, 5, 10, 20, 50, 100, 200, 500], dtype=float)
    norm = BoundaryNorm(boundaries, CMAP.N, clip=False)

    fig, axes = plt.subplots(2, 4, figsize=(7.20, 4.35), sharex=True, sharey=True,
                             gridspec_kw={"hspace": 0.22, "wspace": 0.12})
    mesh = None
    for i, (ax, top) in enumerate(zip(axes.flat, temps)):
        d = grid[np.isclose(grid["Top_K"], top)]
        z = d.pivot(index="R_joint_nOhm", columns="Npw",
                    values="delta_LCOE_global_USD_per_MWh").reindex(index=rj, columns=npw)
        feasible = d.pivot(index="R_joint_nOhm", columns="Npw",
                           values="feasible_r_cryo_only").reindex(index=rj, columns=npw)
        z_plot = np.ma.masked_where(~feasible.to_numpy(dtype=bool), z.to_numpy(dtype=float))
        mesh = ax.pcolormesh(xe, ye, z_plot, cmap=CMAP, norm=norm, shading="flat", rasterized=False)
        bad = np.where(~feasible.to_numpy(dtype=bool), 1.0, np.nan)
        ax.pcolor(xe, ye, bad, facecolor="none", edgecolor="#B0B0B0",
                  hatch="////", linewidth=0.0)
        add_delta_contours(ax, npw, rj, z_plot, label_lines=False)
        ax.plot(
            FIXED_COMPARISON_NPW, FIXED_COMPARISON_RJ_NOHM, marker="D",
            ms=3.6, mfc="white", mec="#222222", mew=0.7, zorder=5,
        )
        opt = summary[np.isclose(summary["Top_K"], top)].iloc[0]
        ax.plot(opt["Npw"], opt["R_joint_nOhm"], marker="*", ms=7.0,
                mfc=RED, mec="white", mew=0.5, zorder=5)
        ax.set_yscale("log")
        ax.set_xlim(xe[0], xe[-1])
        ax.set_ylim(ye[0], ye[-1])
        ax.set_title(f"{top:g} K   $\Delta_{{min}}$={opt['delta_LCOE_global_USD_per_MWh']:.2f}",
                     fontsize=6.7, pad=3)
        ax.text(-0.12, 1.04, chr(ord("a") + i), transform=ax.transAxes,
                fontweight="bold", fontsize=8)
        ax.tick_params(length=2.2, width=0.6)

    for ax in axes[-1, :]:
        ax.set_xlabel(r"Parallel-wound tapes, $N_{pw}$")
        ax.set_xticks([1, 50, 100, 200])
    for ax in axes[:, 0]:
        ax.set_ylabel(r"Joint resistance, $R_j$ (n$\Omega$)")
        ax.set_yticks([1, 3, 10, 30, 100])
        ax.get_yaxis().set_major_formatter(mpl.ticker.ScalarFormatter())

    cbar = fig.colorbar(mesh, ax=axes.ravel().tolist(), orientation="horizontal",
                        fraction=0.055, pad=0.105, aspect=45, ticks=boundaries)
    cbar.set_label(r"Full-plant $\Delta$LCOE relative to the global optimum (US$ MWh$^{-1}$)")
    cbar.ax.tick_params(labelsize=5.7, length=2.0)
    fig.text(0.5, 0.985, "S2 steady-state temperature extension (He, 10 bar)",
             ha="center", va="top", fontsize=7.2, fontweight="bold")
    fig.text(0.5, 0.015, "Star: optimum; open diamond: fixed comparison point; red contour (when present): ΔLCOE = 10",
             ha="center", va="bottom", fontsize=5.7, color=GREY)
    save_bundle(fig, output_dir / "s2_steady_temperature_fig5_like")


def plot_individual_heatmaps(
    grid: pd.DataFrame, summary: pd.DataFrame, output_dir: Path
) -> None:
    """Export one Fig. 5-style heatmap for every operating temperature."""

    temps = sorted(grid["Top_K"].unique())
    npw = np.sort(grid["Npw"].unique().astype(float))
    rj = np.sort(grid["R_joint_nOhm"].unique().astype(float))
    xe = centers_to_edges(npw, log=False)
    ye = centers_to_edges(rj, log=True)
    boundaries = np.array([0, 1, 2, 5, 10, 20, 50, 100, 200, 500], dtype=float)
    norm = BoundaryNorm(boundaries, CMAP.N, clip=False)

    for top in temps:
        d = grid[np.isclose(grid["Top_K"], top)]
        z = d.pivot(
            index="R_joint_nOhm", columns="Npw",
            values="delta_LCOE_global_USD_per_MWh",
        ).reindex(index=rj, columns=npw)
        feasible = d.pivot(
            index="R_joint_nOhm", columns="Npw", values="feasible_r_cryo_only",
        ).reindex(index=rj, columns=npw)
        z_plot = np.ma.masked_where(
            ~feasible.to_numpy(dtype=bool), z.to_numpy(dtype=float)
        )

        fig, ax = plt.subplots(figsize=(3.54, 3.05))
        mesh = ax.pcolormesh(
            xe, ye, z_plot, cmap=CMAP, norm=norm, shading="flat", rasterized=False
        )
        bad = np.where(~feasible.to_numpy(dtype=bool), 1.0, np.nan)
        ax.pcolor(
            xe, ye, bad, facecolor="none", edgecolor="#B0B0B0",
            hatch="////", linewidth=0.0,
        )
        add_delta_contours(ax, npw, rj, z_plot, label_lines=True)
        ax.plot(
            FIXED_COMPARISON_NPW, FIXED_COMPARISON_RJ_NOHM, marker="D",
            ms=4.6, mfc="white", mec="#222222", mew=0.8, zorder=5,
        )
        opt = summary[np.isclose(summary["Top_K"], top)].iloc[0]
        ax.plot(
            opt["Npw"], opt["R_joint_nOhm"], marker="*", ms=8.0,
            mfc=RED, mec="white", mew=0.6, zorder=5,
        )
        ax.set_yscale("log")
        ax.set_xlim(xe[0], xe[-1])
        ax.set_ylim(ye[0], ye[-1])
        ax.set_xticks([1, 20, 50, 100, 200])
        ax.set_yticks([1, 3, 10, 30, 100])
        ax.get_yaxis().set_major_formatter(mpl.ticker.ScalarFormatter())
        ax.set_xlabel(r"Parallel-wound tapes, $N_{pw}$")
        ax.set_ylabel(r"Joint resistance, $R_j$ (n$\Omega$)")
        ax.set_title(
            rf"S2, He 10 bar, {top:g} K; $\Delta_{{min}}$="
            f"{opt['delta_LCOE_global_USD_per_MWh']:.2f}",
            loc="left", fontweight="bold", pad=4,
        )
        ax.tick_params(length=2.2, width=0.6)

        cbar = fig.colorbar(
            mesh, ax=ax, orientation="vertical", fraction=0.052, pad=0.035,
            ticks=boundaries,
        )
        cbar.set_label(r"Full-plant $\Delta$LCOE (US$ MWh$^{-1}$)")
        cbar.ax.tick_params(labelsize=5.6, length=2.0)
        fig.subplots_adjust(left=0.18, right=0.82, bottom=0.23, top=0.90)
        fig.text(
            0.50, 0.025,
            "Star: optimum; diamond: comparison point; red contour (when present): ΔLCOE = 10",
            ha="center", va="bottom", fontsize=5.0, color=GREY,
        )
        tag = f"{top:g}".replace(".", "p")
        save_bundle(fig, output_dir / f"s2_steady_temperature_fig5_like_T{tag}K")

def plot_scenario_comparison(comparison: pd.DataFrame, output_dir: Path) -> None:
    """Compare the S4/S5/S6 HTS-price cases at one common magnet design."""

    scenario_order = ("S4", "S5", "S6")
    expected_prices = {"S4": 100.0, "S5": 50.0, "S6": 10.0}
    required = set(scenario_order)
    observed = set(comparison["scenario"].astype(str))
    if observed != required:
        raise ValueError(f"Expected fixed-design scenarios {sorted(required)}, got {sorted(observed)}")
    if set(comparison["Npw"].astype(int)) != {FIXED_COMPARISON_NPW}:
        raise ValueError("Scenario comparison does not use Npw=30 exclusively")
    if not np.allclose(comparison["R_joint_nOhm"], FIXED_COMPARISON_RJ_NOHM):
        raise ValueError("Scenario comparison does not use R_joint=10 nΩ exclusively")
    for scenario, expected_price in expected_prices.items():
        observed_prices = comparison.loc[
            comparison["scenario"] == scenario, "HTS_price_USD_per_kAm"
        ].unique()
        if len(observed_prices) != 1 or not np.isclose(observed_prices[0], expected_price):
            raise ValueError(f"{scenario} does not use HTS price {expected_price:g}")

    control_columns = [
        "project_lifetime_years", "C0_nonmagnet_USD", "He_price_USD_per_kg",
        "discount_rate", "tmaint_h", "nmaint", "tcool_h", "twarm_h",
        "kdis", "tau_pulse_h", "tau_dwell_h",
    ]
    for column in control_columns:
        if comparison[column].nunique(dropna=False) != 1:
            raise ValueError(f"HTS-price-only comparison control drifted: {column}")

    fig, axes = plt.subplots(1, 2, figsize=(7.20, 2.75), gridspec_kw={"wspace": 0.36})
    for scenario in scenario_order:
        d = comparison[comparison["scenario"] == scenario].sort_values("Top_K")
        t = d["Top_K"].to_numpy(dtype=float)
        lcoe = d["LCOE_plant_USD_per_MWh"].to_numpy(dtype=float)
        delta = d[
            "delta_LCOE_within_scenario_fixed_design_USD_per_MWh"
        ].to_numpy(dtype=float)
        price = float(d["HTS_price_USD_per_kAm"].iloc[0])
        color = SCENARIO_COLORS[scenario]
        label = f"{scenario}  " + "$" + f"{price:g}"

        axes[0].plot(t, lcoe, color=color, lw=1.7, marker="o", ms=3.7)
        axes[0].text(
            40.7, lcoe[-1], f"{label}  {lcoe[-1]:.1f}",
            color=color, va="center", fontsize=5.9,
        )
        axes[1].plot(t, delta, color=color, lw=1.7, marker="o", ms=3.7)
        axes[1].text(
            40.7, delta[-1], f"{label}  {delta[-1]:.1f}",
            color=color, va="center", fontsize=5.9,
        )
        min_idx = int(np.nanargmin(lcoe))
        for ax, values in ((axes[0], lcoe), (axes[1], delta)):
            ax.plot(
                t[min_idx], values[min_idx], marker="*", ms=7.0,
                mfc=color, mec="white", mew=0.5, zorder=5,
            )

    ax = axes[0]
    lcoe_min = float(comparison["LCOE_plant_USD_per_MWh"].min())
    lcoe_max = float(comparison["LCOE_plant_USD_per_MWh"].max())
    lcoe_span = max(lcoe_max - lcoe_min, 1.0)
    ax.set_xlim(3.3, 46.0)
    ax.set_ylim(lcoe_min - 0.10 * lcoe_span, lcoe_max + 0.12 * lcoe_span)
    ax.set_xticks(sorted(comparison["Top_K"].unique()))
    ax.set_xlabel("Operating temperature (K)")
    ax.set_ylabel(r"Full-plant LCOE (US$ MWh$^{-1}$)")
    ax.set_title("Absolute LCOE", loc="left", fontweight="bold")
    ax.text(-0.16, 1.05, "a", transform=ax.transAxes, fontweight="bold", fontsize=8)

    ax = axes[1]
    max_delta = float(comparison[
        "delta_LCOE_within_scenario_fixed_design_USD_per_MWh"
    ].max())
    ax.axhspan(0, 10, color=LIGHT_BLUE, alpha=0.55, zorder=0)
    ax.axhline(10, color=RED, lw=1.0, ls="--", zorder=1)
    ax.text(39.7, 10.5, r"$\Delta$LCOE = 10", ha="right", va="bottom",
            color=RED, fontsize=5.9)
    ax.set_xlim(3.3, 46.0)
    ax.set_ylim(-0.5, max(11.5, max_delta * 1.14))
    ax.set_xticks(sorted(comparison["Top_K"].unique()))
    ax.set_xlabel("Operating temperature (K)")
    ax.set_ylabel(r"Within-price-case $\Delta$LCOE (US$ MWh$^{-1}$)")
    ax.set_title("Temperature penalty at fixed design", loc="left", fontweight="bold")
    ax.text(-0.16, 1.05, "b", transform=ax.transAxes, fontweight="bold", fontsize=8)

    fig.subplots_adjust(left=0.09, right=0.89, bottom=0.25, top=0.82, wspace=0.36)

    fig.text(
        0.50, 0.985,
        r"HTS-price-only sensitivity at fixed $N_{pw}=30$, $R_j=10$ n$\Omega$ (He, 10 bar)",
        ha="center", va="top", fontsize=7.1, fontweight="bold",
    )
    fig.text(
        0.50, 0.015,
        "S4/S5/S6: HTS price = 100/50/10 constant-2025-US$ kA$^{-1}$ m$^{-1}$; star: minimum across tested temperatures",
        ha="center", va="bottom", fontsize=5.4, color=GREY,
    )
    save_bundle(
        fig,
        output_dir / "s4_s5_s6_fixed_design_temperature_comparison_Npw30_Rj10",
    )


def main() -> None:
    if cfg.DEVICE != EXPECTED_DEVICE:
        raise RuntimeError(
            f"This manuscript plot requires FUSION_DEVICE={EXPECTED_DEVICE}; "
            f"got {cfg.DEVICE}."
        )
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path,
                        default=cfg.OUTPUTS_TABLES_DIR / "s2_steady_temperature_extension_8T")
    parser.add_argument("--output-dir", type=Path,
                        default=cfg.OUTPUTS_FIGURES_DIR / "s2_steady_temperature_extension_8T")
    args = parser.parse_args()
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()
    grid = pd.read_csv(input_dir / "s2_steady_temperature_full_grid.csv")
    summary = pd.read_csv(input_dir / "s2_steady_temperature_optimized.csv")
    comparison = pd.read_csv(input_dir / "s4_s5_s6_fixed_design_Npw30_Rj10.csv")
    plot_summary(summary, output_dir)
    plot_heatmaps(grid, summary, output_dir)
    plot_individual_heatmaps(grid, summary, output_dir)
    plot_scenario_comparison(comparison, output_dir)
    print(f"saved figure bundle: {output_dir}")


if __name__ == "__main__":
    main()