"""
4.12_stitch_charging_heatload_timeseries.py

Stitch stacked charging‑heat‑load time‑series plots for different parameter
combinations (Table 1) into a single composite SVG.

- Operating temperatures: 4.2 K / 10 K / 20 K
- Joint resistances: 10 nΩ / 100 nΩ
- For each (temperature, R_joint) pair, generate an 11‑panel figure with:
  (a) A1, (b) B1, (c) B2, (d) C1, (e) C2, (f) C3, (g) C4,
  (h) D1, (i) D2, (j) D3, (k) D4

Layout:
- Row 1: a b c
- Row 2: d e f g
- Row 3: h i j k
Panel labels use plain letters (no parentheses in the final figure).

Legend:
- The legend at the bottom reuses `heat_load_legend.svg` generated by
  `4.10_heatload_2bars.py`, with identical colours and line styles.

Dependency:
- `svgutils` (install via `pip install svgutils`)
"""

from pathlib import Path
import re
from typing import Optional, List, Tuple

import config as cfg

try:
    import svgutils.transform as sg
except ImportError as e:
    raise ImportError(
        "The package `svgutils` is required to stitch SVG figures. "
        "Please install it first with: pip install svgutils"
    ) from e

# Table 1 configuration and panel‑label mapping (consistent with 4.10 / 4.11).
# Config names map to (Npw, rhot) in 4.10 configs; here we only use names for file paths.
TABLE1_LABEL_TO_CONFIG: List[Tuple[str, str]] = [
    ("a", "A1"), ("b", "B1"), ("c", "B2"), ("d", "C1"), ("e", "C2"),
    ("f", "C3"), ("g", "C4"), ("h", "D1"), ("i", "D2"), ("j", "D3"), ("k", "D4"),
]
# Temperature and joint‑resistance combinations (Top = 4.2 / 10 / 20 K, R_joint = 10 / 100 nΩ)
TEMPERATURES_K = [4.2, 10.0, 20.0]
R_JOINT_NOHM_LIST = [10.0, 100.0]

HEATLOAD_BASE = Path(cfg.OUTPUTS_FIGURES_DIR) / "heatload"
OUTPUT_SUBDIR = "charging_timeseries_stitched"
# Layout: first row abc(3), second row defg(4), third row hijk(4)
ROWS_PANELS = [3, 4, 4]  # number of panels per row
N_ROWS = 3
N_COLS = 4
# Legend: reuse `heat_load_legend.svg` generated by 4.10 (identical style)
LEGEND_MARGIN_BOTTOM = 16  # vertical margin below legend (pt)
TOP_MARGIN = 28            # top margin above stitched panels (pt)


def _parse_size(size_str: str) -> float:
    if size_str is None:
        return 0.0
    m = re.findall(r"[0-9.]+", str(size_str))
    return float(m[0]) if m else 0.0


def _get_timeseries_path(T_op: float, R_nohm: float, config_name: str) -> Path:
    """Return path to a single‑config time‑series SVG (same convention as 4.10)."""
    dir_name = f"Top={T_op}K_Rj={R_nohm}nOhm"
    return HEATLOAD_BASE / dir_name / f"config={config_name}" / f"{config_name}_charging_{T_op}K_timeseries.svg"


def _get_legend_path(T_op: float, R_nohm: float) -> Path:
    """Return path to the standalone legend SVG generated by 4.10 (save_legend_only)."""
    dir_name = f"Top={T_op}K_Rj={R_nohm}nOhm"
    return HEATLOAD_BASE / dir_name / "config=A1" / cfg.LEGEND_IMAGE_FILE


def stitch_charging_timeseries_one(T_op: float, R_nohm: float) -> Optional[Path]:
    """
    For a given (T_op, R_joint) pair, stitch 11 stacked charging‑heat‑load
    time‑series subfigures into a single SVG, labelled a–k.
    Layout: row 1 (a b c), row 2 (d e f g), row 3 (h i j k).
    """
    panel_entries = []  # (root, row_idx, col_idx, label)
    panel_w = None
    panel_h = None

    # Row offsets: row 1 starts at 0, row 2 at 3, row 3 at 7
    row_starts = [0, 3, 7]
    for idx, (label, config_name) in enumerate(TABLE1_LABEL_TO_CONFIG):
        svg_path = _get_timeseries_path(T_op, R_nohm, config_name)
        if not svg_path.exists():
            print(f"[warning] Missing timeseries SVG: {svg_path}")
            continue
        fig = sg.fromfile(str(svg_path))
        root = fig.getroot()
        size_w, size_h = fig.get_size()
        w = _parse_size(size_w)
        h = _parse_size(size_h)
        panel_w = w if panel_w is None else max(panel_w, w)
        panel_h = h if panel_h is None else max(panel_h, h)
        row_idx = 2 if idx >= 7 else (1 if idx >= 3 else 0)
        col_idx = idx - row_starts[row_idx]
        panel_entries.append((root, row_idx, col_idx, label))

    if not panel_entries or panel_w is None or panel_h is None:
        print(f"[warning] T_op={T_op}K Rj={R_nohm}nOhm has insufficient subfigures; skipping.")
        return None

    margin_x = panel_w * 0.06
    margin_y = panel_h * 0.06
    label_font_size = 26
    top_label_height = label_font_size + 8

    # Legend: reuse the `heat_load_legend.svg` generated by 4.10
    legend_path = _get_legend_path(T_op, R_nohm)
    legend_h = 0.0
    legend_w = 0.0
    legend_root = None
    if legend_path.exists():
        try:
            fig_legend = sg.fromfile(str(legend_path))
            legend_root = fig_legend.getroot()
            lw, lh = fig_legend.get_size()
            legend_w = _parse_size(lw)
            legend_h = _parse_size(lh)
        except Exception:
            legend_root = None
            legend_w = legend_h = 0.0
    legend_height = legend_h + LEGEND_MARGIN_BOTTOM if legend_root is not None else 0.0

    subplot_area_w = margin_x * (N_COLS + 1) + panel_w * N_COLS
    subplot_area_h = margin_y * (N_ROWS + 1) + panel_h * N_ROWS
    total_w = subplot_area_w
    total_h = TOP_MARGIN + top_label_height + subplot_area_h + legend_height

    fig_out = sg.SVGFigure(f"{total_w}pt", f"{total_h}pt")
    subplot_start_x = margin_x
    subplot_start_y = TOP_MARGIN + top_label_height

    placed_roots = []
    for root, row_idx, col_idx, label in panel_entries:
        x = subplot_start_x + col_idx * (panel_w + margin_x)
        y = subplot_start_y + row_idx * (panel_h + margin_y)
        root.moveto(x, y)
        placed_roots.append((root, label, x, y, row_idx, col_idx))
    fig_out.append([r[0] for r in placed_roots])

    if legend_root is not None:
        legend_x = max(0, (total_w - legend_w) / 2)
        legend_y = total_h - legend_height
        legend_root.moveto(legend_x, legend_y)
        fig_out.append([legend_root])

    out_dir = HEATLOAD_BASE / OUTPUT_SUBDIR
    out_dir.mkdir(parents=True, exist_ok=True)
    T_str = f"{int(T_op)}K" if T_op in (10.0, 20.0) else f"{T_op}K"
    out_name = f"charging_heatload_timeseries_stitched_Top{T_str}_Rj{int(R_nohm)}nOhm.svg"
    out_path = out_dir / out_name
    fig_out.save(str(out_path))

    # Add (a)–(k) style labels
    import xml.etree.ElementTree as ET
    tree = ET.parse(str(out_path))
    root_svg = tree.getroot()
    svg_ns = None
    for key, uri in root_svg.attrib.items():
        if key.startswith("xmlns") and "svg" in uri.lower():
            svg_ns = uri
            break
    if svg_ns is None:
        svg_ns = "http://www.w3.org/2000/svg"
    ET.register_namespace("", svg_ns)
    root_svg.set("width", f"{total_w}pt")
    root_svg.set("height", f"{total_h}pt")
    root_svg.set("viewBox", f"0 0 {total_w} {total_h}")
    labels_group = ET.SubElement(root_svg, f"{{{svg_ns}}}g", {"id": "panel_labels"})

    for root, label, x, y, row_idx, col_idx in placed_roots:
        # Place (a), (b), ... at the inner upper‑left corner of each panel
        label_x = x + 14
        label_y = y - label_font_size -4
        text_elem = ET.SubElement(labels_group, f"{{{svg_ns}}}text", {
            "x": str(label_x),
            "y": str(label_y),
            "font-family": "Arial, sans-serif",
            "font-size": str(label_font_size),
            "font-weight": "bold",
            "text-anchor": "start",
            "dominant-baseline": "hanging",
            "fill": "black",
        })
        text_elem.text = label

    root_svg.remove(labels_group)
    root_svg.append(labels_group)
    tree.write(str(out_path), encoding="utf-8", xml_declaration=True)
    print(f"Saved stitched charging timeseries figure: {out_path}")
    return out_path


def stitch_all_charging_timeseries():
    """Generate stitched figures for all (Top, R_joint) combinations."""
    if not HEATLOAD_BASE.exists():
        print(f"[error] Base directory does not exist: {HEATLOAD_BASE}")
        print("Please run `4.10_heatload_2bars.py` first to generate charging time‑series plots.")
        return
    count = 0
    for T_op in TEMPERATURES_K:
        for R_nohm in R_JOINT_NOHM_LIST:
            p = stitch_charging_timeseries_one(T_op, R_nohm)
            if p is not None:
                count += 1
    print(f"\nStitched {count} composite figures into: {HEATLOAD_BASE / OUTPUT_SUBDIR}")


if __name__ == "__main__":
    stitch_all_charging_timeseries()
